name: Publish Image
description: Publish Image

inputs:
  registry:
    description: The image registry to use for publishing.
    required: true
    default: ghcr.io
  registry_username:
    description: The username to use when logging into the image registry.
    required: true
  registry_password:
    description: The password to use when logging into the image registry.
    required: true
  dockerfile:
    description: The dockerfile to use for the build.
    required: true
  image_name:
    description: The name of the image being published.
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry}}
        username: ${{ inputs.registry_username}}
        password: ${{ inputs.registry_password }}

    - name: Build and push to the GitHub Container Registry
      uses: docker/build-push-action@v6
      with:
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ${{ inputs.dockerfile }}
        context: docker
        push: true
