name: Backup Container Mongo - Image Publish

on:
  release:
    types: [published, edited]

jobs:
  docker:
    # Ensure this only runs on the main repository so we're not publishing images to other repositories.
    if: ${{ github.event.repository.full_name == 'bcgov/backup-container' }}

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Lowercase repo owner
        id: lowercase_repo_owner
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository_owner }}

      - name: Build and publish the image
        uses: ./.github/actions/publish-image
        with:
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: docker/Dockerfile_Mongo
          image_name: ${{ steps.lowercase_repo_owner.outputs.lowercase }}/backup-container-mongo
